// import { Geist, Geist_Mono } from "next/font/google";
// import RequireAuth from "@/components/RequireAuth";
// import "./globals.css";
// import Header from "./components/Header";
// import { GoogleOAuthProvider } from "@react-oauth/google";
// import FacebookSDK from "./components/FacebookSDK";
// //import Sidebar from "./components/LeftSidebar";
// import { Provider } from "react-redux";
// import { PersistGate } from "redux-persist/integration/react";
// import { store, persistor } from "../store/store.js";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
// //       >
// //         {/*<Sidebar />*/}
// //         <GoogleOAuthProvider
// //           clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
// //         >
// //           <FacebookSDK />
// //           <div className="flex-1 bg-[#EFF3FB]">
// //             <RequireAuth>
// //               {/* <Header /> */}
// //               {children}
// //             </RequireAuth>
// //           </div>
// //         </GoogleOAuthProvider>
// //       </body>
// //     </html>
// //   );
// // }
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
//         <Provider store={store}>
//           <PersistGate loading={null} persistor={persistor}>
//             <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
//               <FacebookSDK />
//               <div className="flex-1 bg-[#EFF3FB]">
//                 <RequireAuth>
//                   {children}
//                 </RequireAuth>
//               </div>
//             </GoogleOAuthProvider>
//           </PersistGate>
//         </Provider>
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import RequireAuth from "@/components/RequireAuth";
import "./globals.css";
import Header from "./components/Header";
import { GoogleOAuthProvider } from "@react-oauth/google";
import FacebookSDK from "./components/FacebookSDK";
// import Sidebar from "./components/LeftSidebar";
import Providers from "@/components/Providers"; 
import Script from "next/script";
import FloatingIcons from "@/app/components/FloatingIcons";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
        <Script src="https://cdn.lordicon.com/lordicon.js" strategy="beforeInteractive" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lora:wght@400;700&family=Roboto+Serif:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <div className="z-1">
         <FloatingIcons />
         </div>
        <Providers>
          <GoogleOAuthProvider
            clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
          >
            <FacebookSDK>
             <div className="w-full min-h-screen bg-white dark:bg-gray-900 transition-colors duration-300">
              <RequireAuth>{children}</RequireAuth>
            </div>

            </FacebookSDK>
          </GoogleOAuthProvider>
        </Providers>
      </body>
      
    </html>
  );
}
